<a href="https://colab.research.google.com/github/srcorreia3001/An-lise_Relacional_e_Consultas_SQL_para_Neg-cios/blob/main/An%C3%A1lise_Relacional_e_Consultas_SQL_para_Neg%C3%B3cios.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.
import kagglehub
fareselgohary003_superstore_dataset_path = kagglehub.notebook_output_download('fareselgohary003/superstore-dataset')

print('Data source import complete.')

In [ ]:
import os
import pandas as pd
import sqlite3

#Carregando os arquivos da tabela
caminho_arquivo = '/kaggle/input/notebooks/fareselgohary003/superstore-dataset/final_dataset.xlsx'
df = pd.read_excel(caminho_arquivo)

#Criando uma conexão com o banco de dados SQlite local
conexao = sqlite3.connect('banco_vendas.db')
#Transformando o dataframe do pandas em uma tabela sql chamada vendas
df.to_sql('vendas',conexao,if_exists='replace',index=False)

print("Banco de dados SQlite criado e tabela 'vendas' pronta para uso!")

Banco de dados SQlite criado e tabela 'vendas' pronta para uso!

In [ ]:
#Verificando os nomes exatos das colunas criadas na tabela SQl
colunas_sql = pd.read_sql("PRAGMA table_info(vendas);",conexao)
display(colunas_sql)

    cid           name       type  notnull dflt_value  pk
0     0         Row ID    INTEGER        0       None   0
1     1       Order ID       TEXT        0       None   0
2     2     Order Date  TIMESTAMP        0       None   0
3     3      Ship Date  TIMESTAMP        0       None   0
4     4      Ship Mode       TEXT        0       None   0
5     5    Customer ID       TEXT        0       None   0
6     6  Customer Name       TEXT        0       None   0
7     7        Segment       TEXT        0       None   0
8     8        Country       TEXT        0       None   0
9     9           City       TEXT        0       None   0
10   10          State       TEXT        0       None   0
11   11    Postal Code    INTEGER        0       None   0
12   12         Region       TEXT        0       None   0
13   13     Product ID       TEXT        0       None   0
14   14       Category       TEXT        0       None   0
15   15   Sub-Category       TEXT        0       None   0
16   16   Product Name       TEXT        0       None   0
17   17          Sales       REAL        0       None   0
18   18       Quantity    INTEGER        0       None   0
19   19       Discount       REAL        0       None   0
20   20         Profit       REAL        0       None   0
21   21           Year    INTEGER        0       None   0
22   22          Month    INTEGER        0       None   0
23   23     Month Name       TEXT        0       None   0
24   24  Shipping Days    INTEGER        0       None   0
25   25  Profit Margin       REAL        0       None   0
26   26    Order Month       TEXT        0       None   0
27   27         Cohort       TEXT        0       None   0
28   28  Customer Type       TEXT        0       None   0

In [ ]:
import pandas as pd

#Consulta ao banco de dados sql
query_basica = """
    SELECT [Customer Name], City, Sales, Profit
    FROM vendas
    WHERE Sales > 1000
    ORDER BY Sales DESC
    LIMIT 5;
"""
#Executando a consulta ao banco de dados sql e trazendo o resultado para o pandas
resultado_sql = pd.read_sql(query_basica,conexao)

#Exibindo resultado em formato de tabela
display(resultado_sql)

  Customer Name           City      Sales     Profit
0   Sean Miller   Jacksonville  22638.480 -1811.0784
1  Tamara Chand      Lafayette  17499.950  8399.9760
2  Raymond Buch        Seattle  13999.960  6719.9808
3  Tom Ashbrook  New York City  11199.968  3919.9888
4  Hunter Lopez         Newark  10499.970  5039.9856

In [ ]:
import pandas as pd

#Consulta sql utilizando GROUP BY e função de agregação SUM()
query_agrupada = """
    SELECT Category, SUM(Sales) AS Faturamento_Total, SUM(Profit) AS Lucro_Total
    FROM vendas
    GROUP BY Category
    ORDER BY Faturamento_Total DESC;
"""
#Executando a consulta no banco de dados sql
resultado_grupo = pd.read_sql(query_agrupada,conexao)

#Exibindo o Resulta do Agrupado
display(resultado_grupo)

          Category  Faturamento_Total  Lucro_Total
0       Technology        836154.0330  145454.9481
1        Furniture        741999.7953   18451.2728
2  Office Supplies        719047.0320  122490.8008